name: 'Checkout'
description: 'Checks out the repository with application credentials, reusable for other github.com checkouts'
inputs:
  app_id:
    description: 'GitHub App id'
    required: false
  installation_id:
    description: 'GitHub App installation id'
    required: false
  private_key:
    description: 'GitHub App private key'
    required: true

runs:
  using: 'composite'
  steps:
  - id: create-token
    uses: tpokki/github-actions/token@dev
    with:
      app_id: ${{ inputs.app_id }}
      installation_id: ${{ inputs.installation_id }}
      private_key: ${{ inputs.private_key }}
  - uses: actions/checkout@v3
    with:
      token: ${{ steps.create-token.outputs.token }}
  - shell: bash
    run: |
      git config --global url."https://x-access-token:${{ steps.create-token.outputs.token }}@github.com".insteadOf https://github.com
      git config user.name github-actions
      git config user.email github-actions@github.com
