name: 'List Repositores'
description: 'Lists all repository clone urls for current organization/owner'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  extractedField:
    description: 'The name of the field that is extraected from list of repositories. Default is "name"'
    required: false
    default: 'name'
  topic:
    description: 'Filter repositories by topic'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
